import '@/styles/globals.css';
import '@/styles/app.css';
import '@/styles/bulma.css';

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Script from 'next/script';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script defer="true" src="/octavalidate.js" />
      <body>
        {/* <Navbar /> */}
        {children}
        <Footer />
      </body>
    </html>
  )
}
